const sampleTimelineData: TimelineEventData[] = [
  {
    id: 'event-vivo-start',
    date: '2018 – 2019',
    title: 'First steps with Vivo',
    category: 'Mobile Photography',
    description: 'Started with a Vivo phone, capturing simple moments that sparked my passion.',
    photoGroupDescription: 'Raw campus life and candid shots, full of youthful energy. Started with some good portraits and symmetry.',
    eventProfileImageUrl: 'https://i.postimg.cc/zvndDjGJ/DSC-1129.jpg',
    media: [
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/j2zmpzQB/IMG-20190604-182315-01-01-Original.jpg',
        altText: 'Early Vivo shot - Landscape',
        description: 'A misty morning landscape captured with Vivo.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/J0qK3KQ7/IMG-20200208-174105-Original-2.jpg',
        altText: 'Early Vivo shot - Macro',
        description: 'Close-up of a flower, exploring macro.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/Y0GwDwgX/IMG-20190704-175804-Original.jpg',
        altText: 'Early Vivo shot - Portrait',
        description: 'An early attempt at a street portrait.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/5976pZ6L/IMG-20191128-010649-Original.jpg',
        altText: 'Early Vivo shot - Portrait',
        description: "A flower in bloom, capturing nature's beauty.",
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/d06q3yCr/IMG-20190524-123833-Original.jpg',
        altText: 'Early Vivo shot - Portrait',
        description: 'And my first visit to the beautiful Ellora Caves.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/T3qtNpPH/IMG-20190818-173615-01-Original.jpg',
        altText: 'Early Vivo shot - Portrait',
        description: 'On a Rainy day, back 2019',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/k5LRxymr/IMG-20181230-100435-Original.jpg',
        altText: 'Early Vivo shot - Portrait',
        description: 'Symmetry',
      },
    ],
  },
  {
    id: 'event-camera-iphoneA',
    date: '2020 – 2021',
    title: 'From Vivo to iPhone',
    category: 'Photography & Videography',
    description: 'Moved to better gear and honed my skills through new creative possibilities.',
    photoGroupDescription: 'Portraits and street scenes with sharper focus and emotion.',
    eventProfileImageUrl: 'https://picsum.photos/seed/me_camera_iphoneA/100/100',
    media: [
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/Jh16tSNY/IMG-8748-Original.jpg',
        altText: 'Early video edit with iPhone',
        description: 'Experimenting with video on the iPhone.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/Ls84kwyW/IMG-5598-Original.jpg',
        altText: 'First camera photo',
        description: 'One of my first shots with the new DSLR.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/6p1c5TQq/IMG-9696.avif',
        altText: 'First camera photo',
        description: 'One of my first shots with the new DSLR.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/02PTJmXW/IMG-6558.avif',
        altText: 'Early video edit with iPhone',
        description: 'Experimenting with video on the iPhone.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/XNch3qNw/IMG-2813-Original.jpg',
        altText: 'iPhone A photography example',
        description: 'Discovering the capabilities of iPhone photography.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/CxZD77FM/IMG-9008.avif',
        altText: 'iPhone A photography example',
        description: 'Discovering the capabilities of iPhone photography.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/1t0D6zyp/IMG-8919.avif',
        altText: 'iPhone A photography example',
        description: 'Discovering the capabilities of iPhone photography.',
      },
    ],
  },
  {
    id: 'event-client-dslr',
    date: '2021 – 2022',
    title: 'Mastering the DSLR: Professional Gear & Techniques',
    category: 'Professional Growth',
    description: 'Transitioned to DSLR, unlocking full control and creative freedom.',
    photoGroupDescription: 'Rich, detailed shots showing advanced photography skills.',
    eventProfileImageUrl: 'https://picsum.photos/seed/me_client/100/100',
    media: [
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/SsssqsHV/BIRD-FINAL.jpg',
        altText: 'Client Project Sample 1',
        description: 'Shot from a local event coverage.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/R0mSh1ZV/IMG-2615.jpg',
        altText: 'Client Project Sample 1',
        description: 'Shot from a local event coverage.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/MZgvxQVX/IMG-5644.jpg',
        altText: 'Client Project Sample 1',
        description: 'Shot from a local event coverage.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/fTZbT84J/IMG-5606.jpg',
        altText: 'New DSLR quality',
        description: 'Testing the limits of the new DSLR.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/Z5Hb9BB8/IMG-20200110-142714-Original.jpg',
        altText: 'New DSLR quality',
        description: 'Testing the limits of the new DSLR.',
      },
      {
        type: MediaType.Image,
        src: 'https://i.postimg.cc/P5p0Gk6Z/IMG-5232-Original-Original.jpg',
        altText: 'Client Project Sample 2',
        description: 'Product photography for a small business.',
      },
    ],
  },
  {
    id: 'event-editing-mastery',
    date: '2021 – Present',
    title: 'The Art of Transformation: Before & After Edits',
    category: 'Photo Editing',
    description: 'Editing turns raw shots into stories with color and mood.',
    photoGroupDescription: 'Side-by-side images showing transformation and creativity.',
    quotes: [
      'See the magic behind every frame.',
      'The real story lies beneath the surface.',
    ],
    eventProfileImageUrl: 'https://i.postimg.cc/zvndDjGJ/DSC-1129.jpg',
    media: [
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/QC1HSC7x/IMG-2357.jpg',
        afterSrc: 'https://i.postimg.cc/GmcHJcmd/IMG-2622.jpg',
        altText: 'Nature Photography Edit',
        description: 'Nature shot: Enhanced colors, contrast, and mood in Lightroom.',
        src: '',
      },
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/prfLz7Nm/IMG-2609.jpg',
        afterSrc: 'https://i.postimg.cc/wB1x0388/IMG-2610.jpg',
        altText: 'Product Photography Edit',
        description: 'Product photo: Refined colors and product enhancement in Photoshop.',
        src: '',
      },
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/59B4PZG0/IMG-2471.jpg',
        afterSrc: 'https://i.postimg.cc/4NwJGpXR/IMG-2329.jpg',
        altText: 'Wildlife Photography Edit',
        description: 'Wildlife capture: Enhanced details and dramatic mood.',
        src: '',
      },
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/BQzV2vg1/IMG-2458.jpg',
        afterSrc: 'https://i.postimg.cc/3JkLrTTr/IMG-2577.jpg',
        altText: 'Wildlife Photography Edit',
        description: 'Wildlife scene: Improved contrast and color balance.',
        src: '',
      },
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/1zB0cCQY/IMG-2613.jpg',
        afterSrc: 'https://i.postimg.cc/R0mSh1ZV/IMG-2615.jpg',
        altText: 'Wildlife Photography Edit',
        description: 'Bird photography: Enhanced details and natural colors.',
        src: '',
      },
      {
        type: MediaType.BeforeAfter,
        beforeSrc: 'https://i.postimg.cc/85svdTwj/IMG-2628.jpg',
        afterSrc: 'https://i.postimg.cc/GhDNRyGh/IMG-2614.jpg',
        altText: 'Wildlife Photography Edit',
        description: 'Wildlife portrait: Improved lighting and mood.',
        src: '',
      },
    ],
  },
  {
    id: 'event-upgraded-iphone-reels',
    date: '2021 – Present',
    title: 'Moving Moments: Storytelling with Instagram Reels',
    category: 'Mobile Content Creation',
    description: 'Telling stories through short, moving clips on social media.',
    photoGroupDescription: 'Dynamic, lively moments captured in video snippets.',
    quotes: [
      'Every reel is a heartbeat shared.',
      'Slowing life down to remember it better.',
    ],
    eventProfileImageUrl: 'https://picsum.photos/seed/me_iphone_pro/100/100',
    media: [
      {
        type: MediaType.InstagramReel,
        src: 'https://player.vimeo.com/video/1088597919?h=7f0c8f7c7c',
        altText: 'Recent Instagram Reel',
        description: 'A quick edit for an Instagram Reel.',
      },
      {
        type: MediaType.InstagramReel,
        src: 'https://player.vimeo.com/video/1088598102?h=7f0c8f7c7c',
        altText: 'Advanced iPhone photo - Night mode',
        description: 'Exploring night mode on the new iPhone.',
      },
      {
        type: MediaType.InstagramReel,
        src: 'https://player.vimeo.com/video/1088598048?h=7f0c8f7c7c',
        altText: 'Advanced iPhone photo - Night mode',
        description: 'Exploring night mode on the new iPhone.',
      },
      {
        type: MediaType.InstagramReel,
        src: 'https://player.vimeo.com/video/1088598021?h=7f0c8f7c7c',
        altText: 'Advanced iPhone photo - Night mode',
        description: 'Exploring night mode on the new iPhone.',
      },
      {
        type: MediaType.InstagramReel,
        src: 'https://player.vimeo.com/video/1088598077?h=7f0c8f7c7c',
        altText: 'Advanced iPhone photo - Cinematic',
        description: 'Attempting a cinematic shot with iPhone.',
      },
    ],
  },
];
